export enum JavaType {
  BYTE = "java.lang.Byte",
  DOUBLE = "java.lang.Double",
  FLOAT = "java.lang.Float",
  INTEGER = "java.lang.Integer",
  LONG = "java.lang.Long",
  SHORT = "java.lang.Short",
  BOOLEAN = "java.lang.Boolean",
  STRING = "java.lang.String",
  DATE = "java.util.Date",
  BIG_DECIMAL = "java.math.BigDecimal",
  BIG_INTEGER = "java.math.BigInteger",
  ARRAY_LIST = "java.util.ArrayList",
  UNMODIFIABLE_COLLECTION = "java.util.Collections$UnmodifiableCollection",
  UNMODIFIABLE_SET = "java.util.Collections$UnmodifiableSet",
  UNMODIFIABLE_MAP = "java.util.Collections$UnmodifiableMap",
  HASH_SET = "java.util.HashSet",
  HASH_MAP = "java.util.HashMap",
  OPTIONAL = "java.util.Optional",
  ENUM = "java.lang.Enum"
}
